### ISSUE TITLE
Update!!

### ISSUE THREAD

**Issue by rickdaalhuizen90** [AO15A1LM/laterna-magica#13]
Op het moment ben ik Malang Indonesie. Heb mijn laptop niet bij dus kan Jullie niet via slack of facebook bereiken. Ik maak op het moment gebruik van een internet cafe dat nog op windows xp draait dus probeer ff op deze manier een berichtje te versturen. 

Zouden jullie het werk dat tot nu toe is gemaakt willen commiten zodat ik er verder mee aan de slag kan gaan? Het is pas na de vakantie dat wij verder gaan met het project dus voor nu hoef er niks nieuws worden gedaan. 

Als het mogelijk is zou ik jullie graag woensdag tussen 11 en 12 via slack willen bellen? Je kan gewoon een berichtje op slack achter laten. Woensdag ben ik namelijk weer terug in Surabaya.

Groet,
Rick

**Comment by Matthbo** [comment]
@kfortuin en ik willen morgen nog iets langer doorgaan aan de sprint.
Kevin moest nog wat aan zijn forms doen en ik moet nog de read maken zodat je meer kan zien dan alleen de plan naam en de eind datum.
Zodra we daar mee klaar zijn zullen we alles committen en mergen.
