### ISSUE TITLE
Tasks kunnen nog niet verwijdert worden

### ISSUE THREAD

**Issue by Matthbo** [AO15A1LM/laterna-magica#17]
De delete knop leid naar een niet bestaande url, de delete functionaliteit is nog niet gemaakt.

Todo:
delete in TaskController
delete view (delete.blade.php)

**Comment by kfortuin** [comment]
Vind ik ook niet heel gek. De branch was nog niet eens af dus ik weet niet waarom hier al een pull request voor is aangemaakt?

**Comment by Matthbo** [comment]
Check slack daar leg ik uit dat ik alles aan het voorbereiden om na de vakantie verder te gaan

**Comment by kfortuin** [comment]
Opgelost in de feature/tasks branch
